title: Beautifully Bipolar
email: kellysnyder@live.com
baseurl: '/'

theme_colors: # enclose hex codes in ' '
  theme: '#4B201A'
  text: '#58595e'
  background: '#fff'
  code-block: '#fbf8f4'

header_pages:
  - index.md
  - blog.md
  - art.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
