title: Beautifully Bipolar
author: UnKn0WN
email: kellysnyder@live.com
baseurl: '/'

theme_colors: # enclose hex codes in ' '
  theme: '#4B201A'
  text: '#58595e'
  background: '#fff'
  code-block: '#fbf8f4'

header_pages:
  - index.md
  - blog.md
  - art.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

jekyll_compose:
  default_front_matter:
    drafts:
      layout: default
      photo:
      caption_header:
      caption: 
      category: photoblog
      published: true
    posts:
      layout: post
      photo:
      title: 
      category: blog1
      published: true
    photopost:
      layout: default
      photo:
      caption_header:
      caption: 
      category: photoblog
      published: true
